export let users = [
  {
    id: 1,
    username: "user1",
    name: "Alice Smith",
    password: "password1",
    profilePicture: "https://placeimg.com/64/64/people/1",
    gender: "Female",
  },
  {
    id: 2,
    username: "user2",
    name: "Bob Johnson",
    password: "password2",
    profilePicture: "https://placeimg.com/64/64/people/2",
    gender: "Male",
  },
  {
    id: 3,
    username: "user3",
    name: "Charlie Brown",
    password: "password3",
    profilePicture: "https://placeimg.com/64/64/people/3",
    gender: "Male",
  },
  {
    id: 4,
    username: "user4",
    name: "Daisy Adams",
    password: "password4",
    profilePicture: "https://placeimg.com/64/64/people/4",
    gender: "Female",
  },
  {
    id: 5,
    username: "user5",
    name: "Evan Rogers",
    password: "password5",
    profilePicture: "https://placeimg.com/64/64/people/5",
    gender: "Male",
  },
  {
    id: 6,
    username: "user6",
    name: "Fiona Graham",
    password: "password6",
    profilePicture: "https://placeimg.com/64/64/people/6",
    gender: "Female",
  },
  {
    id: 7,
    username: "user7",
    name: "George King",
    password: "password7",
    profilePicture: "https://placeimg.com/64/64/people/7",
    gender: "Male",
  },
  {
    id: 8,
    username: "user8",
    name: "Hannah Scott",
    password: "password8",
    profilePicture: "https://placeimg.com/64/64/people/8",
    gender: "Female",
  },
  {
    id: 9,
    username: "user9",
    name: "Ivan Lee",
    password: "password9",
    profilePicture: "https://placeimg.com/64/64/people/9",
    gender: "Male",
  },
  {
    id: 10,
    username: "user10",
    name: "Julia Davis",
    password: "password10",
    profilePicture: "https://placeimg.com/64/64/people/10",
    gender: "Female",
  },
];
